---
title: "Preliminary Oral Exam"
description: "My experience with the preliminary oral exam"
author:
  - name: Cindy Fang
    affiliation: Johns Hopkins Bloomberg School of Public Health
date: 2025-02-23
categories: [oral exam, studying]  
draft: false
---
The Biostatistics PhD program at Johns Hopkins has several major requirements throughout the five-year degree. In the first year, students are required to take coursework and write the comprehensive exam at the end of the four terms. In the third year, students take the preliminary oral exam to advance to candidacy. Finally, in the fifth year, students defend their theses. This blog post is about the preliminary oral exam.

# What is the preliminary oral exam?

The preliminary oral exam is taken by PhD students at some point during their third year of study and upon passing the exam, students obtain the status of PhD candidate. To take the exam, students must first begin by forming a committee of five professors in total. There are strict requirements for the composition of the committee that I won't go into detail about here. The exam itself is roughly 2 hours long, consisting of a 15-20 minutes long presentation from the student on their current research, followed by 60-90 minutes of questions from the committee members. After the questioning period, the student leaves the room and the committee members discuss the student's performance. The committee then votes on whether the student has passed the exam. The guidelines for the exam are as follows:

"The purpose of this [preliminary] examination is to determine whether the student has both the ability and knowledge to undertake significant research in his/her general area of interest. Specifically, the examiners will be concerned with the student's: (1) capacity for logical thinking; (2) breadth of knowledge in relevant areas; and (3) ability to develop and conduct research leading to a completed thesis."


# Scheduling
One of the most annoying aspects of this exam is actually the scheduling. Unsurprisingly, it is difficult for five busy academics to find a common 2 hour block of time to meet. Our department's academic adminstrator was able to handle all the scheduling for me. I simply had to provide her with a list of the committee members' names and contact information, as well as a rough date for when I wanted to take my oral exam.

I initially tried to schedule my exam for the end of December, so that I could (hopefully) relax and celebrate over the winter holidays. However, there was not a single 2 hour block of time in December when my committee members were all free. Instead, I pushed the date back to the middle of January, and ended up scheduling for January 10th, before the start of classes in the School of Public Heatlh. 

The most obvious downside to scheduling an exam for immediately after the winter holidays is that you will likely spend your holidays working. This ended up being the case for me, although I worked at a much more relaxed pace than usual. One upside to studying through the holidays is that your collaborators will be on break, which means you have fewer responsibilities and distractions from your studies. Another perk is that picking a date before the start of classes made scheduling much easier, since most professors won't have any teaching during this time. I can't say whether or not I recommend this strategy because it will depend highly on your preferred working style and family obligations during the holidays.

# Studying for the exam

I started studying in earnest for my oral exam a little more than a month in advance. At this point, I put my research on hold and instead focused on reviewing important concepts and literature in genomics. I created a document with a list of different topics that I thought I might get asked about. I also kept track of questions that came up while reading papers or discussing my research with classmates, and made sure to ask my advisor these questions during our weekly meeting. This was probably one of the most useful things I did to prepare, as my advisor agreed to meet with me for an extra 30 minutes every week and I found these discussions to be extremely productive. 

I also reviewed the coursework from my first year in the program, with a focus on concepts from the Advanced Methods sequences such as GLMs. I use GLMs in my research so I thought this would be low-hanging fruit for committee members to ask about, and it did indeed come up during my exam. I probably spent a bit too much time on re-deriving equations but I found that this gave me some much-needed confidence. 

Since my research involves using non-negative matrix factorization, I felt it was necessary to review some basic linear algebra results. I reviewed some basic definitions, the rank-nullity theorem, and the spectral theorem. I even practiced writing some basic proofs just to make sure I understood what I was doing. Unsurprisingly, none of this stuff actually showed up on my exam so I wouldn't recommend studying these topics if they aren't directly relevant to your research. However, it did give me a confidence boost and I had been intending to review linear algebra for a while anyway. 

# During the exam

I had already given several talks about my research at conferences and seminars by this point, so I wasn't really nervous about presenting, but I was extremely nervous for the subsequent questioning. I prepared over 70 slides for the exam. About 20 of these slides were the main presentation, and the remaining 50 were supplemental slides that I could refer to if asked. I found it helpful to organize the supplemental slides by topic, so that I could easily find the slide I needed during the exam. 

The questions I received from my committee members were all related to my research. The questions spanned a wide variety of topics, from genomics ("Why do we log-transform counts data in scRNA-seq analyses?"), GLMs ("What is the relationship between a Poisson GLM and a multinomial GLM?"), machine learning ("What is cross-validation and what are some disadvantages?"), neuroscience ("Why do we care about the different layers in the cortex?"), and public health ("What's the difference between race and ancestry?"). I had the most difficulty answering the public health questions because I hadn't spent a lot of time thinking about the downstream applications of my research. For anyone working on projects that are more discovery-oriented and less translational, I would recommend giving some thought to questions in this vein. 

# After the exam

After I had answered all the questions, my committee asked me to wait outside the examination room while they deliberate. I couldn't help but try to eavesdrop while this went on but unfortunately I was distracted by a louder conversation happening across the hall. After I was invited back into the room, I was notified that I had passed the exam. Each of my committee members gave me feedback on my presentation and my responses to their questions, and congratulated me on my progress thus far. I was pretty ecstatic at this point 

# Closing thoughts

A common piece of advice (or perhaps consolation) that I heard often leading up to the exam is something along the lines of "You don't need to stress, you know much more than you think you do!". While I appreciate the sentiment and the goodwill behind these words, I found out while studying that sometimes you know much _less_ than you think you do. In my honest opinion, you really do need to take the exam seriously and dedicate a substantial amount of time to studying, if not for the knowledge then at least for the confidence boost. Aside from the exam itself, I realized there were major gaps in my knowledge of the literature that I am grateful I filled while studying for the exam. Now that I am more than a month out from my exam, I find that the things I learned in preparation have been useful for my research, and I am glad to have invested the time to learn them.

